name: Data Refresh

on: [push]
  #schedule:
  #  - cron:  '0 * * * *'
jobs:
  build:
    name: coronavirus dataset refresh
    runs-on: macOS-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install dependencies
        run: Rscript -e "install.packages(c('dplyr', 'lubridate', 'usethis', 'remotes'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Refresh the data
        run: Rscript ./data_raw/data_refresh.R
      - name: Push the updates
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git config --global user.name 'RamiKrispin'
              git config --global user.email 'ramkrisp@umich.edu'
              git commit -am "coronavirus dataset autoupdate"
              git push
          fi
